### ISSUE TITLE
Several small issues found

### ISSUE THREAD

**Issue by yo3hcv** [heartoftechnology/embedded-printf#1]
Hello Christean,

Great job with this tiny printf! Several small issues found :)

`if (embpf_InternalFlags && FLAG_HEX_USE_CAPITALS)`
shall be
`if (embpf_InternalFlags & FLAG_HEX_USE_CAPITALS)`

This typo can be found in several places with other flags :)

You should clear all flags here
`		/* When a '%' is encountered it means formatting is required. */
		else
		{
			embpf_InternalFlags = 0; /* clear internal flags */`

and remove any individual clearing
`embpf_InternalFlags &= ~FLAG_IS_NOT_FIRST_DIGIT;`

because you forgot to clear on %d cases :)

br/
Edi

**Comment by christe4nm** [comment]
Hi Edi,
Thanks and good catch! Should be fixed now. 
Should you find yourself looking for something more capable than what I have, have a look at [eyalroz/printf](https://github.com/eyalroz/printf). It is actively worked on and can do way more than my barebones stuff.
